import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, team, analytics  }) {
  return (
    <html lang="en">
      <body>
        {children}
        {team}
        {analytics}
        </body>
    </html>
  );
}
