import "./globals.css";
import ThemeProvider from './context/ThemeProvider'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, team, analytics  }) {
  const value = {
    theme: 'dark',
    name: 'leichao'
  }
  return (
    <html lang="en">
      <body>
       <ThemeProvider value={value}>{children}</ThemeProvider>
        {/* 下面这2个会影响SSG渲染 */}
        {/* {team}
        {analytics} */}
        </body>
    </html>
  );
}
